# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BdPDOk0eK6t4hL3IwoNO5Fqbch1pX70b
"""

dict1 = {"one":1,"two":2,"three":3}
print("Dictionary:",dict1)

def sum_list(mylist):
  sum = 0
  for item in mylist:
    sum = sum + item
  print("Sum of all the items in the given list is:",sum)
sum_list([1,5,2,8,0,3,9,4,5,1,5,6,2,7])

n = int(input("Enter number of empty dictionaries: "))
mydict = {}
mylist = [mydict] * n
print("List of",n,"empty dictionaries:",mylist)

dict1 = {"blue":1, "green":2, "yellow":3, "red":4, "black":5, "purple":6}
print("Given dictionary:",dict1)
mylist = list(dict1)
index = 0
for item in mylist:
  print("Index ",index,"has:",mylist[index])
  index = index + 1

dict1 = {"blue":1, "green":2, "yellow":3, "red":4, "black":5, "purple":6}
print("Given dictionary:",dict1)
print("Keys present in the given dictionary:")
for item in dict1:
  print(item)
 
print("Values present in the given dictionary:")
for item in dict1.values():
  print(item)
 
print("Key:Value pairs in the given dictionary:")
for (k,v) in dict1.items():
  print(k,":",v)

dict1 = {1:100, 2:200, 3:300, 4:400, 5:500}
print("Given dictionary:",dict1)
sum=0
for value in dict1.values():
  sum = sum + value
print("Sum of all the values in the given dictionary:",sum)
 
for key in dict1.keys():
  sum = sum + key
print("Sum of all keys in the given dictionary:",sum)

dict1 = {1:10, 2:20}
dict2 = {3:30, 4:40}
dict3 = {5:50, 6:60}
dict2.update(dict3)
dict1.update(dict2)
print("Required result:",dict1)

t1 = (1,2,3,4,5)
print(t1, type(t1))

t1 = (1,2.5,"Bonjour",["Hello",1,6])
print(t1, type(t1))

t1 = ("N","i","m","b","u","s")
str = "".join(t1)
print("Tuple converted string:",str)

t1 = (1,2,3,4,5,6,7,8,9,10)
slice_tup = (t1[2:6])
print("Sliced tuple:",slice_tup)

t1 = (("one",1),("two",2),("three",3),("four",4),("five",5))
converted_dict = dict(t1)
print("Converted Dictionary:",converted_dict)

t1 = (1,2,3,4,5,6,7,8,9,10)
print("Reversed Tuple:",t1[::-1])

mylist = [("one",1),("two",2),("three",3),("four",4)]
dict_converted = dict(mylist)
print("Dictionary converted list:",dict_converted)

mylist = ["Hello","Hey","Hi","Hola","Bonjour"]
print("Tuple converted list:",tuple(mylist))