# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mYa5JAcchtFN9jPwkIIutwrr4pljxN3G
"""

p=2
t=3
r=5
Si=p*t*r/100
print(Si)



r=10
A=22/7*r*r
print(A)

b=int(input('enter the value b'))
h=int(input('enter the value h'))
a=b*h/2
print(b)

l=int(input("enter the value of l"))
b=int(input("enter the value of b"))
A=l*b
print(A)

a=int(input('enter the value a'))
p=4*a
print(p)



r=int(input("enter the value r"))
c=2*22/7*r
print(c)

a=int(input("enter value a"))
b=int(input("enter value b"))
print(a+b)
print(a-b)
print(a%b)
print(a/b)
print(a//b)

a=float(input("enter the value of a"))
c=int(input("entet the value of c"))
temp,a=a,c
c=temp
print(a,c)

c=float(input("enter the value c"))
f=(c*1.8)+32
print(f)



